CREATE DATABASE catalog;
USE catalog;

CREATE TABLE item(id INT GENERATED BY DEFAULT AS IDENTITY, 
publish_date DATE, 
archived BOOLEAN,
 books_id INT, 
 genre INT NOT NULL,
 PRIMARY KEY (id),
  FOREIGN KEY (books_id)
   REFERENCES books(id));
  foreign key(genre) REFERENCES genre(id),

CREATE TABLE books(id INT GENERATED BY DEFAULT AS IDENTITY, 
publisher VARCHAR,
 cover_state VARCHAR);






CREATE TABLE genre (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30),
    items VARCHAR(30)
);

CREATE TABLE musicAlbum(
   id INT NOT NULL AUTO_INCREMENT,
   on_spotify BOOLEAN,
   publish_date DATE,
   archived boolean       
);
